on:
  push: ~
  pull_request: ~

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "unit-testing"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'macos-latest', 'macos-10.15' ]
        php: [ 7.0 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: zip, :xdebug
          tools: composer

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.php }}-composer-

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist

      - name: Run tests
        run: |
          php ./.github/scripts/generate_pdf.php > ./artifacts/test.pdf

      - name: Archive logs artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            artifacts
